# Generated by Django 4.1.5 on 2023-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='M_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
