# Generated by Django 4.1.5 on 2023-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_m_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='M_number',
            field=models.CharField(max_length=11),
        ),
    ]
