# Generated by Django 4.1.5 on 2023-01-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
